export const RECEIVE_CARDS = 'RECEIVE_CARDS';
export const DELETE_CARD = 'DELETE_CARD';
export const VOTES_UPDATED = 'SERVER_ACTION/VOTES_UPDATED'
export const CREATE_CARD = 'SERVER_ACTION/CREATE_CARD'

